---
title: "Decision tree"
author: "Priyanka Mohekar"
date: "2 May 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
library(tree)
```

## Decision tree
```{r}
adv <- read.csv("Advertising.csv")
model_tree <- tree(sales ~TV, data = adv) 
model_tree
{{plot(model_tree)
  text(model_tree)}}
summary(model_tree)
library(dplyr)
adv %>% filter(TV < 122.05) %>% summarise(n()) 
adv %>% filter(TV > 122.05) %>% summarise(mean(sales)) 
adv %>% filter(TV < 122.05) %>% summarise(mean(sales)) 
```


```{r}
partition.tree(model_tree)
sort(adv$TV)
## (0.7+4.1)/2
adv %>% filter(TV < 2.4) %>% summarise(mean(sales)) 
adv %>% filter(TV > 2.4) %>% summarise(mean(sales)) 
adv %>% filter(TV > 134.75) %>% summarise(mean(sales)) 
adv %>% filter(TV < 134.75) %>% summarise(n()) 
```

#no of averages for cut
```{r}
TV_uniqs = sort(unique(adv$TV))

for (i in seq(1, length(TV_uniqs)-1)) {
  curr_cut = (TV_uniqs[i] + TV_uniqs[i+1])/2
  print(curr_cut)  
}
```

## root node cut
```{r}
TV_uniqs = sort(unique(adv$TV))

cuts = c()
mses = c()
for (i in seq(1, length(TV_uniqs)-1)) {
  curr_cut = (TV_uniqs[i] + TV_uniqs[i+1])/2
  cuts = c(cuts, curr_cut)
  samples_left = adv %>% filter(TV < curr_cut)
  samples_right = adv %>% filter(TV > curr_cut)
  avg_left = mean(samples_left$sales)
  avg_right = mean(samples_right$sales)
  adv$predicted_sales = if_else(adv$TV < curr_cut, avg_left, avg_right)
  curr_mse = sum((adv$sales - adv$predicted_sales)^2)/nrow(adv)
  mses = c(mses, curr_mse)
}
models_perf = data_frame(TV_cuts = cuts, MSE = mses)
models_perf %>% arrange(MSE) %>% head(1)
```


## 2nd branch cut (1 depth dowm)
```{r}
TV_uniqs = sort(unique(adv$TV))

cuts = c()
mses = c()
adv_temp = adv %>% filter(TV < 122.05)
for (i in seq(1, length(TV_uniqs)-1)) {
  curr_cut = (TV_uniqs[i] + TV_uniqs[i+1])/2
  cuts = c(cuts, curr_cut)
  samples_left = adv_temp %>% filter(TV < curr_cut)
  samples_right = adv_temp %>% filter(TV > curr_cut)
  avg_left = mean(samples_left$sales)
  avg_right = mean(samples_right$sales)
  adv_temp$predicted_sales = if_else(adv_temp$TV < curr_cut, avg_left, avg_right)
  curr_mse = sum((adv_temp$sales - adv_temp$predicted_sales)^2)/nrow(adv_temp)
  mses = c(mses, curr_mse)
}
models_perf = data_frame(TV_cuts = cuts, MSE = mses)
models_perf %>% arrange(MSE) %>% head(1)

adv %>% filter(TV < 30.05) %>% summarise(n())
```


```{r}
model_tree <- tree(sales ~TV+radio+newspaper, data = adv) 
model_tree
{{plot(model_tree)
  text(model_tree)}}
```