---
title: "7th Day ML"
author: "Priyanka Mohekar"
date: "16 May 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(rattle)
library(tree)
library(rpart)
library(caret)
```


```{r}
set.seed(123)
hr <- read.csv("C:/Users/Administrator/Desktop/Machine Learning/Datasets/datasets-master/HR Analytics.csv")
#View(hr)
dim(hr)
hr_train = hr[1:(0.7*nrow(hr)),]
hr_test = hr[(0.7*nrow(hr)+1):nrow(hr),]
nrow(hr_train)
nrow(hr_test)
```
```{r}
model = rpart(Attrition~., data = hr_train, method = "class")
pred = predict(model, hr_test)
result = as.data.frame(pred)
hr_test$predict = ifelse(result$`0`>0.5,0,1)
hr_test$predict = factor(hr_test$predict)
confusionMatrix(hr_test$predict, hr_test$Attrition, positive = "1")
table(hr_train$Attrition)
857/nrow(hr_train)
```

```{r}
library(randomForest)
hr_train$Attrition = as.factor(hr_train$Attrition)
mtry = round(sqrt(length(colnames(hr_train))-1))
model_rf = randomForest(Attrition~. , data = hr_train,
                        ntree = 400,
                        mtry = mtry)
hr_test$predicted = predict(model_rf, hr_test)
hr_test$predicted = factor(hr_test$predicted)
hr_test$Attrition = factor(hr_test$Attrition)
cm = confusionMatrix(hr_test$predicted, hr_test$Attrition, positive = "1")
cm$overall['Accuracy']*100
cm$byClass['Sensitivity']
10/857
146/172
```
```{r}
acc_vals = c()
sens_vals = c()
for (i in 10:400) {
  hr_train$Attrition = as.factor(hr_train$Attrition)
  mtry = round(sqrt(length(colnames(hr_train))-1))
  model_rf = randomForest(Attrition~. , data = hr_train,
                          ntree = i,
                          mtry = mtry)
  hr_test$predicted = predict(model_rf, hr_test)
  hr_test$predicted = factor(hr_test$predicted)
  hr_test$Attrition = factor(hr_test$Attrition)
  cm = confusionMatrix(hr_test$predicted, hr_test$Attrition, positive = "1")
  accu = cm$overall['Accuracy']*100
  sens = cm$byClass['Sensitivity']*100
  acc_vals = append(acc_vals, accu)
  sens_vals = append(sens_vals,sens)
}

head(acc_vals)
head(sens_vals)

plot(acc_vals, type='l')
plot(sens_vals, type = 'l')
```


## Mannual calculation for Random Forest
```{r}
input_predictors = colnames(hr_train %>% select(-Attrition))
input_predictors

mtry = round(sqrt(length(input_predictors)))
mtry

ntree = 10
#ntree = 400
result = data.frame(actual = hr_test$Attrition)
for (i in seq(1,ntree)) {
    sample_predictors = input_predictors[sample(1:length(input_predictors), mtry)]
    sample_index = sample(seq(1, nrow(hr_train)),(0.6*nrow(hr_train)))
    sample_data = hr_train[sample_index, c(sample_predictors,"Attrition")]
    curr_model = rpart(Attrition~., data = sample_data )
    #hr_test[,paste0('tree_', i , collapse = '')] =predict(curr_model,hr_test %>% select(sample_predictors), type = 'class')
    result[,paste0('tree_',i,collapse = '')]=predict(curr_model,hr_test %>% select(sample_predictors), type = 'class')
    }

View(hr_test %>% select(sample_predictors))
#result$x = seq(1, nrow(hr_test))
#dim(sample_data)

View(result)

result$count_0 = rowSums((result %>% select(-actual)) == 0)
result$count_1 = rowSums((result %>% select(-actual)) == 1)
result$final = ifelse(result$count_0>result$count_1,0,1)

View(result)
```

```{r}
dim(result)
table(result$final, result$actual)
376/nrow(result)
mean(result$actual == result$final)
```



```{r}
library(adabag)
hr_train$Attrition = as.factor(hr_train$Attrition)
hr_train = hr[1:(0.7*nrow(hr)),]
model_boost = boosting(Attrition~., data = hr_train)
predict_obj = predict(model_boost, hr_test)
hr_test$pred = predict_obj$class
hr_test$Attrition = as.factor(hr_test$Attrition)
hr_test$pred = as.factor(hr_test$pred)
confusionMatrix(hr_test$pred, hr_test$Attrition, positive = "1")
```



