---
title: "8th Day ML"
author: "Priyanka Mohekar"
date: "18 May 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(BBmisc)
library(dplyr)
library(ggplot2)
library(corrplot)
library(heatmaply)
```

```{r}
odi = read.csv("C:/Users/Administrator/Desktop/Machine Learning/Datasets/datasets-master/odi-batting.csv")
odi$century = ifelse(odi$Runs>99,1,0)
odi$ducks = ifelse(odi$Runs==0,1,0)
odi$above_150 = ifelse(odi$Runs>149,1,0)
odi$fifties = ifelse(odi$Runs>49 & odi$Runs<100, 1, 0)
odi$missed_centuries = ifelse(odi$Runs>90 & odi$Runs<100, 1, 0)
#View(odi)
```


## Create KPI metrics 
```{r}
players_summary = odi %>% group_by(Player) %>% summarise(
  matches = n(),
  total_runs = sum(Runs, na.rm = T),
  avg_runs = mean(Runs, na.rm = T),
  centuries = sum(century, na.rm = T),
  ducks = sum(ducks, na.rm = T),
  fifties = sum(fifties, na.rm = T),
  above_150 = sum(above_150, na.rm =T),
  missed_centuries = sum(missed_centuries, na.rm =T) 
)
View(players_summary)
```


```{r}
top_players = players_summary %>% arrange(-total_runs) %>% head(100) 
data_kmeans = top_players %>% select(-Player)
data_norm = normalize(data_kmeans,method = "range" ,range = c(0,1))
model_kmeans = kmeans(data_norm, centers = 10)
top_players$cluster = model_kmeans$cluster
barplot(table(top_players$cluster))
data_norm$cluster = top_players$cluster
#cmdscale()
```


## Cluster charecteristics
```{r}
model_kmeans$centers
```

### Within square sums
```{r}
model_kmeans$withinss
```

### Between square sums
```{r}
model_kmeans$betweenss
```


### Plotting totalwithinss vs Number of clusters
```{r}
model_kmeans$tot.withinss
```

```{r}
dim(data_norm)
dim(as.matrix(dist(data_norm %>% select(-cluster))))
data_norm_2d = cmdscale(dist(data_norm %>% select(-cluster)))
dim(data_norm_2d)
data_norm_2d = as.data.frame(data_norm_2d)
plot(data_norm_2d)
View(data_norm_2d)
data_norm_2d$cluster = data_norm$cluster
ggplot(data_norm_2d, aes(x = V1, y = V2, color = factor(cluster)))+
  geom_point()
```

```{r}
set.seed(123)
hr <- read.csv("C:/Users/Administrator/Desktop/Machine Learning/Datasets/datasets-master/HR Analytics.csv")
hr_subset = hr %>% select(Age, MonthlyIncome)
hr_subset_norm = normalize(hr_subset, method = "range", range = c(0,1))
model_hr = kmeans(hr_subset_norm, centers = 5)
hr_subset$cluster = as.factor(model_hr$cluster)
ggplot(hr_subset, aes(x = Age, y = MonthlyIncome, color = cluster))+
  geom_point(position = "jitter")
```

#Hierarchical clustering
## For large data its slow
```{r}
names(data_norm)
hclust_model = hclust(dist(data_norm %>%  select(-cluster)))
tree = plot(hclust_model)
```


```{r}
data_norm$cluster = cutree(hclust_model, k = 4)

data_norm_2d = cmdscale(dist(data_norm %>% select(-cluster)))
data_norm_2d = as.data.frame(data_norm_2d)
data_norm_2d$cluster = data_norm$cluster
ggplot(data_norm_2d, aes(x = V1, y = V2, color = factor(cluster)))+
  geom_point()
```

```{r}
cor_players = cor(t(data_norm %>% head(10) %>%  select(-cluster)))
corrplot(cor_players)

corrplot(cor_players, order = "hclust", addrect = 2)
```

```{r}
heatmaply(cor_players)
```

